# in dev profile

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
spring:  
  sql:
    init:
      platform: h2 
  jpa:
    show-sql: true

cookies:
  domain: http://localhost:8080
  domainRoot: http://localhost:8080
  
logging:
  level:
    com:
      InventoryManagement: DEBUG
    org:
      springframework: 
        web: DEBUG
        security: DEBUG

management:
  endpoints:
    web: #jmx:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

#springdoc:
#  api-docs:
#    path: path=/api-docs